// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class Product
    {
        public Product()
        {
            Comment = new HashSet<Comment>();
            ReceiptDetail = new HashSet<ReceiptDetail>();
            Tag = new HashSet<Tag>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string PriceSale { get; set; }
        public string Code { get; set; }
        public int? CategoryId { get; set; }
        public int? SupplierId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public int? UserId { get; set; }
        public string Slug { get; set; }
        public double? Discount { get; set; }
        public string Quantity { get; set; }
        public string Content { get; set; }

        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<ReceiptDetail> ReceiptDetail { get; set; }

        public virtual ICollection<Tag> Tag { get; set; }
    }
}