// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class Receipt
    {
        public Receipt()
        {
            ReceiptDetail = new HashSet<ReceiptDetail>();
        }

        public int Id { get; set; }
        public string Total { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public virtual ICollection<ReceiptDetail> ReceiptDetail { get; set; }
    }
}