// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class ReceiptDetail
    {
        public int Id { get; set; }
        public int? ProductId { get; set; }
        public decimal? Price { get; set; }
        public string Discount { get; set; }
        public string Amount { get; set; }
        public int? ReceiptId { get; set; }
        public int? CustomerId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public virtual User Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}