// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class User
    {
        public User()
        {
            Comment = new HashSet<Comment>();
            Product = new HashSet<Product>();
            ReceiptDetail = new HashSet<ReceiptDetail>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public int? RoleId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Avatar { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public DateTime? LastLogin { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ReceiptDetail> ReceiptDetail { get; set; }
    }
}